### ISSUE TITLE
Issues in #marketing.html file.

### ISSUE THREAD

**Issue by anshumangahlot** [PriyaGhosal/SkillWise#613]
# Issues:

1. **Incorrect Meta Description**:

The meta description incorrectly mentions "Modern Physics skills" instead of "digital marketing skills."

2. **Typo in Image Filename**:

The image filename for the "Introduction to Digital Marketing" card is digtal.jpg, which is a typo.

3. **Image Aspect Ratio**:

Images are currently set to a width of 300 and height of 100, which may lead to distortion.

4. **Accessibility of Links**:

Anchor tags do not have visible text, which may hinder accessibility.

6. **Lack of Semantic HTML**:

The HTML structure lacks semantic tags such as header, main, and footer tag.

7. **Insufficient alt Text Descriptions**:

Some alt text descriptions for images are too brief (e.g., "SEO image").

8. **Responsive Design**:

Although the viewport meta tag is included, the CSS needs to ensure responsiveness on different devices.

9. **Duplicate Titles in Course Cards**:

Course titles are quite similar, which may affect SEO.

**Additionally Note**: 
I am submitting a Pull request(#689) which fixes the issues listed above.

**Comment by nevil2006** [comment]
Incorrect Meta Description:

Action: Update the meta description to reflect "digital marketing skills" accurately. Ensure it succinctly summarizes the content of the page while incorporating relevant keywords.
Typo in Image Filename:

Action: Rename the image file from digtal.jpg to digital.jpg to correct the typo and improve file organization.
Image Aspect Ratio:

Action: Adjust the CSS for images to maintain their aspect ratio. You can use properties like object-fit: cover; or max-width: 100%; height: auto; to prevent distortion.
Accessibility of Links:

Action: Ensure all anchor tags contain meaningful text. If the links must be visually hidden, consider using aria-label attributes to maintain accessibility.
Lack of Semantic HTML:

Action: Revise the HTML structure to include semantic tags. For example:
html
Copy code
<header>...</header>
<main>...</main>
<footer>...</footer>
This helps search engines and screen readers better understand the structure of your content.

Insufficient Alt Text Descriptions:

Action: Improve the alt text for images by providing more descriptive text. Instead of just "SEO image," use something like "Illustration of SEO strategies in digital marketing."
Responsive Design:

Action: Review your CSS to ensure it uses relative units (like percentages or em/rem) instead of fixed pixel values. Additionally, use media queries to adapt styles for different screen sizes.
Duplicate Titles in Course Cards:

Action: Differentiate course titles by making them more descriptive or unique. Consider including the specific focus of each course to enhance SEO and clarity.
